exclude = [
    "venv",
    ".venv",
    "migrations",
    ".vscode",
    ".ruff_cache",
]
line-length = 88
indent-width = 4

[lint]
select = ["E","F","I","N","T20","BLE"]
fixable = ["ALL"]

# E501: line too long
ignore = ["E501"]