name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - python: '3.10'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Linting and formatting
      run: |
        ruff check .
        ruff format . --check
    - name: Run Tests
      run: |
        python manage.py test
